server:
  port: 9009

spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.174.129

aliyun:
  sms:
    accessKeyId: ***************** # AccessKey ID (用户AccessKey)
    accessKeySecret: ********************* #Access Key Secret (用户AccessKey)
    template_code: SMS_163432310  #模版CODE: SMS_163432310
    sign_name: 自己做短信测试 #签名名称
